import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    FMP_API_KEY: z.string().min(1),
    ALPHA_VANTAGE_API_KEY: z.string().min(1),
    FINNHUB_API_KEY: z.string().min(1),
    DATABASE_URL: z.string().url(),
    REDIS_URL: z.string().url().optional(),
    CLERK_SECRET_KEY: z.string().min(1),
    WEBSOCKET_URL: z.string().url(),
    NODE_ENV: z.enum(["development", "production", "test"]),
  },
  client: {
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: z.string().min(1),
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: z.string().min(1),
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: z.string().min(1),
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: z.string().min(1),
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: z.string().min(1),
    NEXT_PUBLIC_WS_URL: z.string().url(),
    NEXT_PUBLIC_FINNHUB_API_KEY: z.string().min(1),
    NEXT_PUBLIC_CRYPTOCOMPARE_API_KEY: z.string().min(1),
    NEXT_PUBLIC_NEWSAPI_KEY: z.string().min(1),
    NEXT_PUBLIC_MARKETAUX_API_KEY: z.string().min(1),
  },
  runtimeEnv: {
    FMP_API_KEY: process.env.FMP_API_KEY,
    ALPHA_VANTAGE_API_KEY: process.env.ALPHA_VANTAGE_API_KEY,
    FINNHUB_API_KEY: process.env.FINNHUB_API_KEY,
    DATABASE_URL: process.env.DATABASE_URL,
    REDIS_URL: process.env.REDIS_URL,
    CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
    WEBSOCKET_URL: process.env.WEBSOCKET_URL,
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY,
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_SIGN_UP_URL,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL,
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: process.env.NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL,
    NEXT_PUBLIC_WS_URL: process.env.NEXT_PUBLIC_WS_URL,
    NEXT_PUBLIC_FINNHUB_API_KEY: process.env.NEXT_PUBLIC_FINNHUB_API_KEY,
    NEXT_PUBLIC_CRYPTOCOMPARE_API_KEY: process.env.NEXT_PUBLIC_CRYPTOCOMPARE_API_KEY,
    NEXT_PUBLIC_NEWSAPI_KEY: process.env.NEXT_PUBLIC_NEWSAPI_KEY,
    NEXT_PUBLIC_MARKETAUX_API_KEY: process.env.NEXT_PUBLIC_MARKETAUX_API_KEY,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
});
